### Create a new user
Post http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "222@222.com",
  "password": "111"
}

### sign in user-1
Post http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "111@111.com",
  "password": "111"
}

### sign in user-2
Post http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "222@222.com",
  "password": "111"
}

### get current user
GET  http://localhost:3000/auth/whoami


### Find a particular user with a given ID
GET http://localhost:3000/auth/8

### Find all users with a given email
GET http://localhost:3000/auth?email=111@111.com

### Delete a user with given id
DELETE  http://localhost:3000/auth/2

### Update a user
PATCH   http://localhost:3000/auth/4
Content-Type: application/json

{
  "email": "444@444.com"
}


### Set auth User color
GET http://localhost:3000/auth/colors/red

### GET user color
GET http://localhost:3000/auth/colors
